PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE TIME(
ID INT PRIMARY KEY,
DESCRIPTION TEXT NOT NULL
);
INSERT INTO "TIME" VALUES(0,'1 Action');
INSERT INTO "TIME" VALUES(1,'1 Bonus Action');
INSERT INTO "TIME" VALUES(2,'1 Minute');
INSERT INTO "TIME" VALUES(3,'10 Minutes');
INSERT INTO "TIME" VALUES(4,'1 Hour');
INSERT INTO "TIME" VALUES(5,'8 Hours');
INSERT INTO "TIME" VALUES(6,'12 Hours');
INSERT INTO "TIME" VALUES(7,'24 Hours');
INSERT INTO "TIME" VALUES(8,'Special');
CREATE TABLE SCHOOL(
ID INT PRIMARY KEY,
TITLE TEXT);
INSERT INTO "SCHOOL" VALUES(0,'Abjuration');
INSERT INTO "SCHOOL" VALUES(1,'Conjuration');
INSERT INTO "SCHOOL" VALUES(2,'Divination');
INSERT INTO "SCHOOL" VALUES(3,'Enchantment');
INSERT INTO "SCHOOL" VALUES(4,'Evocation');
INSERT INTO "SCHOOL" VALUES(5,'Illusion');
INSERT INTO "SCHOOL" VALUES(6,'Necromancy');
INSERT INTO "SCHOOL" VALUES(7,'Transmutation');
CREATE TABLE SOURCE(
ID INT PRIMARY KEY,
TITLE TEXT);
INSERT INTO "SOURCE" VALUES(0,'Player''s Handbook');
INSERT INTO "SOURCE" VALUES(1,'Elemental Evil');
INSERT INTO "SOURCE" VALUES(2,'Sword Coast Adventurer''s Guide');
CREATE TABLE SPELLS(
    ID INT PRIMARY KEY,
    NAME TEXT,
    LEVEL INT,
    SCHOOLID INT references SCHOOL(ID),
    TIMEID INT references TIME(ID)
    RITUAL BOOLEAN,
    CONENTRATION BOOLEAN,
    SOURCEID INT references SOURCE(ID),
    RANGE TEXT, 
    COMPONENTS TEXT,
    DURATION TEXT,
    DESCRIPTION TEXT
);
COMMIT;
